# Generated by Django 4.2.26 on 2025-12-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'News Image', 'verbose_name_plural': 'News Images'},
        ),
    ]
