# Generated by Django 4.2.26 on 2026-01-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_newsimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={},
        ),
        migrations.AddField(
            model_name='newsimage',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
